[project]
name = "ElecCalc"
version = "0.1.0"
description = "A simple matrix calculator built in pyside6(Qt) and numpy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.16.0",
    "pyside6>=6.10.0",
]
